spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: SECOND-MICROSERVICE
          uri: lb://SECOND-MICROSERVICE
          predicates:
            - Path=/api/data/**